### ISSUE TITLE
many changes needed 

### ISSUE THREAD

**Issue by vishalx360** [scorelab/ImageLab#27]
[1]  **ImportError**  

running **`$ python app.py `** after installation of required packages gives **error ->** 
```
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    from src.common.database import Database
ImportError: No module named src.common.database
```
* which can be **fixed** by moving app.py to root of directory 

[2] **jinja2.exceptions.TemplateNotFound**

**after moving** app.py to root dir , running app.py gives **error ->** 

`File "/home/ben/.local/lib/python2.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: home.html`

* which can be **fixed** by moving folder _/src/templates_ to same directory as app.py & creating home.html in template folder with this lines, so that it extends base.html->

```{% extends "base.html" %}
{% block content %}
<heading : Welcome to ImageLab homepage>
    <descripition : Machine learning supported web-base image labelling tool for researcher.>
<links to login, register, project, about etc pages
**<content homepage should have>** 
{% endblock %}
```

there are **more** things which needs improvement and fixes, such as ->

- renaming **R**egister.html to **r**egister.html in templates folder.
- removing **`}`** from 162th line of style.css.
- removing duplicates from style.css by folowing **DRY** rule (Do not Repeat Yourself) & removing empty rulesets
- adding **viewport** as -> 
` <meta name="viewport" content="width=device-width, initial-scale=1.0">`
- styling grid properly.
- changing `href` of FAB button from google-homepage to some function which adds project or user on dashboard.
- moving  (navbar) to base.html from project-manager, profile-manager.html .
- changing href of **<a>** imagelab text-logo **#** to **/**  in `<header>`, so by clicking , it will take to homepage.
- etc.

i have made a branch in my forked repo , including these changes mentioned above, which i call [`testy`](https://github.com/vishalx360/ImageLab/tree/testy)

submission for _GCI 2018 task_.

**Comment by vishalx360** [comment]
**some _screenshots_**

**Login page**

![workspace 1_046](https://user-images.githubusercontent.com/25267239/47601208-c8d86680-d9ea-11e8-8d4c-3a8f8b6dd65f.png)

**home page, with added links to other pages and description**

![workspace 1_047](https://user-images.githubusercontent.com/25267239/47601210-cfff7480-d9ea-11e8-9046-9731812e150f.png)
